#occ3d_nuscenes_classes_names = ['others',
#                                'barrier',
#                                'bicycle',
#                                'bus',
#                                'car',
#                                'construction_vehicle',
#                                'motorcycle',
#                                'pedestrian',
#                                'traffic_cone',
#                                'trailer',
#                                'truck',
#                                'driveable_surface',
#                                'other_flat',
#                                'sidewalk',
#                                'terrain',
#                                'manmade',
#                                'vegetation',
#                                'free']

class_names: [ 
# Ordered by occ3d_nuscenes classes mapping (in comments)
#         'others',
#         'barrier',
              "fence",
              "barrier",
              "wall", # is this rly barrier ?
#         'bicycle',
              "bicycle",
#         'bus',
              "bus",
#         'car',
              "car",
#         'construction_vehicle',
              "construction_vehicle",
#         'motorcycle',
              "motorcycle",
#         'pedestrian',
              "pedestrian",
#         'traffic_cone',
              "traffic_cone",
#         'trailer',
              "trailer",
#         'truck',
              "truck",
#         'driveable_surface',
              "road",
#         'other_flat',
#         'sidewalk',
              "sidewalk",
#         'terrain',
              "terrain",
              "flat vegetation",
              "grass", # new classes
              "dirt",
#         'manmade',
              "manmade",
              "building",
              "traffic_sign",
              "pole",
              "traffic_light",
#         'vegetation',
              "vegetation",
              "trunk",
#         'free'
              
              # "road_marking", # useless for occ
              # Removed from wide_classes
              # "SUV",
              # "driveable surface",
              # "bicyclist",
              # "motorcyclist",
              # "walkable",
              # "other_ground",
              # "ground",
              # "parking",
              # "flat_surface",
              # "curb",
              ]
dynamic_class_names: []
